/**
 * @fileoverview ESM mongoose mirror for LeadQuotation.
 * @module models/LeadQuotation
 */
import mongoose from "mongoose";

const leadQuotationSchema = new mongoose.Schema(
  {
    quotation_no: { type: String, required: true, unique: true, index: true },
    ref_no: { type: String, trim: true, default: "" },
    customer_ref: { type: String, trim: true, default: "" },
    lead: { type: mongoose.Schema.Types.ObjectId, ref: "Lead", default: null, index: true },
    party_id: { type: mongoose.Schema.Types.ObjectId, ref: "Party", default: null },
    quotation_date: { type: Date, default: Date.now },
    valid_until: { type: Date },
    validity_days: { type: Number, default: 15 },
    subject: { type: String, trim: true, default: "" },
    customer_name: { type: String, trim: true, default: "" },
    kind_attn: { type: String, trim: true, default: "" },
    phone: { type: String, trim: true, default: "" },
    cell: { type: String, trim: true, default: "" },
    email: { type: String, trim: true, default: "" },
    gstin: { type: String, trim: true, uppercase: true, default: "" },
    address: {
      address_line_1: { type: String, default: "" },
      city: { type: String, default: "" },
      state: { type: String, default: "" },
      pincode: { type: String, default: "" },
      country: { type: String, default: "India" },
    },
    items: [
      {
        product: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
        product_name: { type: String, required: true },
        description: { type: String, default: "" },
        hsn_code: { type: String, default: "" },
        quantity: { type: Number, required: true, default: 1 },
        unit: { type: String, default: "Nos" },
        rate: { type: Number, required: true, default: 0 },
        discount_percent: { type: Number, default: 0 },
        discount_amount: { type: Number, default: 0 },
        taxable_amount: { type: Number, required: true, default: 0 },
        gst_rate: { type: Number, default: 0 },
        cgst_rate: { type: Number, default: 0 },
        cgst_amount: { type: Number, default: 0 },
        sgst_rate: { type: Number, default: 0 },
        sgst_amount: { type: Number, default: 0 },
        igst_rate: { type: Number, default: 0 },
        igst_amount: { type: Number, default: 0 },
        total_gst_amount: { type: Number, default: 0 },
        line_total: { type: Number, required: true, default: 0 },
      },
    ],
    total_discount: { type: Number, default: 0 },
    subtotal: { type: Number, default: 0 },
    total_gst: { type: Number, default: 0 },
    round_off: { type: Number, default: 0 },
    grand_total: { type: Number, default: 0 },
    amount_in_words: { type: String, default: "" },
    terms_and_conditions: [{ type: String }],
    company_name: { type: String, default: "" },
    company_regd_address: { type: String, default: "" },
    company_phone: { type: String, default: "" },
    company_email: { type: String, default: "" },
    company_gstin: { type: String, default: "" },
    bank_name: { type: String, default: "" },
    account_name: { type: String, default: "" },
    account_number: { type: String, default: "" },
    ifsc_code: { type: String, default: "" },
    branch_name: { type: String, default: "" },
    account_type: { type: String, default: "" },
    signatory_name: { type: String, default: "" },
    signatory_phone: { type: String, default: "" },
    signatory_email: { type: String, default: "" },
    signatory_designation: { type: String, default: "" },
    signatory_user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null, index: true },
    sales_person_name: { type: String, trim: true, default: "" },
    sales_person_phone: { type: String, trim: true, default: "" },
    sales_person_email: { type: String, trim: true, default: "" },
    sales_person_designation: { type: String, trim: true, default: "Sales Executive" },
    sales_person_user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null, index: true },
    approval_status: {
      type: String,
      enum: ["pending_approval", "approved", "rejected"],
      default: "pending_approval",
      index: true,
    },
    approved_at: { type: Date, default: null },
    approved_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    rejection_reason: { type: String, default: "" },
    status: {
      type: String,
      enum: ["draft", "pending_approval", "approved", "sent", "in_negotiation", "accepted", "rejected", "expired", "on_hold", "converted"],
      default: "pending_approval",
      index: true,
    },
    version: { type: Number, default: 1 },
    revision_of: { type: mongoose.Schema.Types.ObjectId, ref: "LeadQuotation", default: null, index: true },
    revision_history: [
      {
        version: { type: Number, required: true },
        items: { type: Array, default: [] },
        subtotal: { type: Number, default: 0 },
        total_discount: { type: Number, default: 0 },
        total_gst: { type: Number, default: 0 },
        round_off: { type: Number, default: 0 },
        grand_total: { type: Number, default: 0 },
        amount_in_words: { type: String, default: "" },
        terms_and_conditions: { type: Array, default: [] },
        signatory_name: { type: String, default: "" },
        signatory_user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
        sales_person_name: { type: String, default: "" },
        sales_person_user: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
        status: { type: String, default: "" },
        approval_status: { type: String, default: "" },
        approved_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
        approved_at: { type: Date, default: null },
        saved_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
        saved_at: { type: Date, default: Date.now },
        change_summary: { type: String, default: "" },
      },
    ],
    lost_reason: { type: String, default: "" },
    proforma_issued_at: { type: Date, default: null },
    customer_po_number: { type: String, trim: true, default: "" },
    customer_po_date: { type: Date, default: null },
    advance_amount: { type: Number, default: 0 },
    payment_mode: { type: String, trim: true, default: "" },
    payment_reference: { type: String, trim: true, default: "" },
    proforma_details: {
      proforma_no: { type: String, trim: true, default: "" },
      invoice_date: { type: Date, default: null },
      customer_po_number: { type: String, trim: true, default: "" },
      customer_po_date: { type: Date, default: null },
      sales_person: { type: String, trim: true, default: "" },
      orc: { type: String, default: "na" },
      dispatch_date: { type: Date, default: null },
      freight_charges: { type: String, default: "Extra at actual" },
      payment_terms: { type: String, default: "On Delivery" },
      transport: { type: String, default: "" },
      ship_to_address: { type: String, default: "same as billing" },
      customer_type: { type: String, default: "Dealer" },
      installation_required: { type: String, default: "No" },
      gst_concession: { type: String, default: "na" },
      margin_sheet_attached: { type: String, default: "na" },
      kyc_status: { type: String, default: "na" },
      remarks: { type: String, default: "" },
      generated_at: { type: Date, default: null },
      generated_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    },
    conversion: {
      converted_at: { type: Date, default: null },
      converted_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
      party_id: { type: mongoose.Schema.Types.ObjectId, ref: "Party", default: null },
      order_id: { type: mongoose.Schema.Types.ObjectId, ref: "Order", default: null },
      customer_po_number: { type: String, default: "" },
      customer_po_date: { type: Date, default: null },
      advance_amount: { type: Number, default: 0 },
      payment_mode: { type: String, default: "" },
      payment_reference: { type: String, default: "" },
      notes: { type: String, default: "" },
    },
    next_follow_up_at: { type: Date, default: null, index: true },
    last_follow_up_at: { type: Date, default: null },
    expiry_alert_sent_at: { type: Date, default: null },
    validity_extension_history: [
      {
        extended_at: { type: Date, default: Date.now },
        extended_by: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        previous_valid_until: { type: Date },
        new_valid_until: { type: Date },
        reason: { type: String, default: "" },
      },
    ],
    created_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    updated_by: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    deletedAt: { type: Date, default: null, index: true },
  },
  { timestamps: true }
);

export default mongoose.models.LeadQuotation || mongoose.model("LeadQuotation", leadQuotationSchema);
