import {
  ArrowDown,
  ArrowUp,
  Ban,
  CheckCircle2,
  FileEdit,
  Flame,
  FolderOpen,
  LayoutGrid,
  ListChecks,
  Minus,
  Navigation,
  PackageCheck,
  PauseCircle,
  RotateCcw,
  ShieldCheck,
  Truck,
  XCircle,
  type LucideIcon,
} from "lucide-react";

const TAB_ICON_BY_ID: Record<string, LucideIcon> = {
  all: LayoutGrid,
  pending_admin_approval: ShieldCheck,
  due_sheet_pending: FileEdit,
  pending_account_approval: ShieldCheck,
  pending_finance_approval: ShieldCheck,
  pending_approvals: ListChecks,
  pending_approval: ListChecks,
  approval_pending: ListChecks,
  pending_transport: Truck,
  transport_pending: Truck,
  transport_return_pending: Truck,
  in_transit: Navigation,
  pending_delivery: PackageCheck,
  returns_pending: RotateCcw,
  return_pending: RotateCcw,
  open: FolderOpen,
  open_dispatched: PackageCheck,
  closed: CheckCircle2,
  closed_delivered: PackageCheck,
  on_hold: PauseCircle,
  rejected: XCircle,
  cancelled: Ban,
  draft: FileEdit,
  low: ArrowDown,
  normal: Minus,
  high: ArrowUp,
  urgent: Flame,
  // Entity list status / type tabs
  available: CheckCircle2,
  assigned: Truck,
  on_trip: Truck,
  leave: PauseCircle,
  inactive: Ban,
  active: CheckCircle2,
  customer: FolderOpen,
  supplier: PackageCheck,
  both: ListChecks,
  maintenance: PauseCircle,
  blacklisted: Ban,
  owned: CheckCircle2,
  leased: FolderOpen,
  third_party: Truck,
  courier: Truck,
  internal: PackageCheck,
};

export function getOrderListTabIcon(tabId: string): LucideIcon {
  return TAB_ICON_BY_ID[tabId] ?? FolderOpen;
}
